LoSaS/Fight/urls.py
from django.urls import path
from . import views

app_name = 'Fight'
urlpatterns = [
    path('battle/', views.battle, name='battle'),
    path('countdown/', views.countdown, name='countdown'),
    path('fight_selector/', views.fight_selector, name='fight_selector'),
]

LoSaS/Home/urls.py
""" Defines URL patterns for Home. """

from django.urls import path

from . import views

app_name = 'Home'
urlpatterns = [
    path('', views.home, name='home')
]

LoSaS/LoSaS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('team/', include('Team.urls')),
    path('users/', include('Users.urls')),
    path('world/', include('World.urls')),
    path('bots_farm/', include('Bots_Farm.urls')),
    path('fight', include('Fight.urls')),
    path('items', include('Items.urls')),
    path('inventory', include('Inventory.urls')),
    path('cities/', include('Cities.urls')),
    path('blacksmith/', include('Blacksmith.urls')),
    path('arena/', include('Arena.urls')),
    path('tavern/', include('Tavern.urls')),
    path('jeweler/', include('Jeweler.urls')),
    path('carpentry_shop/', include('Carpentry_Shop.urls')),
    path('clothier/', include('Clothier.urls')),
    path('armorer/', include('Armorer.urls')),
    path('boss_fight/', include('Boss_Fight.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

LoSaS/Users/urls.py
from django.urls import path, include
from . import views

app_name = 'Users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

LoSaS/World/urls.py
""" Defines URL patterns for World. """

from django.urls import path

from . import views

app_name = "World"
urlpatterns = [
    path('main/', views.main , name='main')
]

LoSaS/Home/models.py
from django.db import models

# Create your models here.

LoSaS/Home/views.py
from django.shortcuts import render
from Fight.views import countdown

def home(request):
    """ Main page for app Home """
    return render (request, 'Home/home.html')

def countdown(request):
    return render (request, 'Home/base.html')

LoSaS/Home/templates/Home/base.html
{% load bootstrap4 %}
{% load static %}

<input type="hidden" id="user-id" value="{% if user.is_authenticated %}{{ user.id }}{% endif %}">

<!doctype html>
<html lang="eng">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>Lands of Swords and Sorcery</title>

      {% bootstrap_css %}
      {% bootstrap_javascript jquery='full' %}
      <script src="{% static 'Fight/js/countdown.js' %}"></script>
    </head>

    <body>

      <nav class="navbar navbar-expend-md navbar-dark bg-dark mb-4 ">

          {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'World:main' %}">World</a>
            <span id="countdown" data-remaining-time="{{ remaining_time }}" data-redirect-url="{% url 'Fight:battle' %}" style="font-weight: bold; color: white;">{{ time_to_display }}</span>
            <a class="navbar-brand" href="{% url 'Users:logout' %}">Logout</a>
          {% else %}
            <a class="navbar-brand" href="{% url 'Home:home' %}">Home</a>
          {% endif %} 


      </nav>

      <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
          {% block page_header %}{% endblock page_header %}
        </div>
        <div>
          {% block content %}{% endblock content %}
        </div>
      </main>
    </body>
  </html> 

LoSaS/Home/templates/Home/home.html
{% extends "Home/base.html" %}

{% load static %}

{% block content %}
    <body style="background-image: url('{% static 'background/Background.jpg' %}'); background-size: cover; background-repeat: no-repeat;">
        <div class="row rounded" style="background-color: DarkGray">
            <header>
                <h1>Welcome to the Lands of Sword and Sorcery</h1>
            </header>
        </div>

        <div class="row mt-4">
            <div class="col text-center d-flex justify-content-center">
                <a class="btn btn-primary border border-secondary" href="{% url 'Users:register' %}" style="background-color: DarkGray; color: black; font-weight: bold;">Register</a>
                <a class="btn btn-primary border border-secondary ml-3" href="{% url 'Users:login' %}" style="background-color: DarkGray; color: black; font-weight: bold;">Login</a>
            </div>
        </div>
     
            <section class="hero row rounded mt-3" style="background-color: DarkGray">
                <h2>Embark on an Epic Journey</h2>
                <p>Welcome to the mystical world of Sword and Sorcery, a realm filled with magic, monsters, and adventure. As a brave adventurer, you'll face formidable challenges, forge alliances, and unravel the secrets of a world threatened by a rising evil.</p>
            </section>


            <section class="world-history row rounded mt-3" style="background-color: DarkGray">
                <h2>The Tale of Sword and Sorcery</h2>
                <p>In the ancient lands of Sword and Sorcery, a once-peaceful world is now on the brink of darkness. A malevolent force has risen, shrouding the realm in chaos and despair. This newly born evil has united monstrous hordes and wicked sorcerers, posing a dire threat to the entire world.</p>
                <p>It is a time for heroes to rise, for the races of this land to unite, and for adventurers to journey into the heart of darkness. Will you stand against the tide of evil, or will you succumb to the malevolence that seeks to engulf the Lands of Sword and Sorcery?</p>
            </section>

            <section class="features row rounded mt-3" style="background-color: DarkGray">
                <h2>Game Features</h2>
                <ul>
                    <li>Choose from a variety of races and classes for your character.</li>
                    <li>Engage in epic battles against hordes of monsters and rival players.</li>
                    <li>Explore a rich and immersive medieval fantasy world.</li>
                    <li>Uncover the deep lore and secrets of the realm as you progress in the game.</li>
                    <li>Form alliances, forge friendships, and face challenges together with other players.</li>
                </ul>
            </section>
 
        <footer>
            <section class="features row rounded mt-3" style="background-color: DarkGray">
                <p>&copy; 2023 Lands of Sword and Sorcery. All rights reserved.</p>
            </section>
        </footer>
    </body>
{% endblock content %}