LoSaS/Home/urls.py
""" Defines URL patterns for Home. """

from django.urls import path

from . import views

app_name = 'Home'
urlpatterns = [
    path('', views.home, name='home')
]

LoSaS/LoSaS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('team/', include('Team.urls')),
    path('users/', include('Users.urls')),
    path('world/', include('World.urls')),
    path('bots_farm/', include('Bots_Farm.urls')),
    path('fight', include('Fight.urls')),
    path('items', include('Items.urls')),
    path('inventory', include('Inventory.urls')),
    path('cities/', include('Cities.urls')),
    path('blacksmith/', include('Blacksmith.urls')),
    path('arena/', include('Arena.urls')),
    path('tavern/', include('Tavern.urls')),
    path('jeweler/', include('Jeweler.urls')),
    path('carpentry_shop/', include('Carpentry_Shop.urls')),
    path('clothier/', include('Clothier.urls')),
    path('armorer/', include('Armorer.urls')),
    path('boss_fight/', include('Boss_Fight.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

LoSaS/Tavern/urls.py
from django.urls import path
from . import views

app_name = 'Tavern'
urlpatterns = [
    path('task_master/', views.task_master, name='task_master'),
    path('activate_task/<int:task_id>/', views.activate_task, name='activate_task'),
    path('complete_task/<int:task_id>/', views.complete_task, name='complete_task'),
    path('claim_reward/<int:task_id>/', views.claim_reward, name='claim_reward'),
    path('reset_tasks/', views.reset_tasks, name='reset_tasks'),  # Nowa ścieżka
]

LoSaS/World/urls.py
""" Defines URL patterns for World. """

from django.urls import path

from . import views

app_name = "World"
urlpatterns = [
    path('main/', views.main , name='main')
]

LoSaS/Tavern/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task_name = models.CharField(max_length=100)
    task_description = models.TextField()
    enemies_to_defeat = models.PositiveIntegerField(default=0)
    gold_to_earn = models.PositiveIntegerField(default=0)
    players_to_defeat = models.PositiveIntegerField(default=0)
    gold_reward = models.PositiveIntegerField(default=0)
    is_completed = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} - {self.task_name}"

LoSaS/Tavern/views.py
from django.shortcuts import render, redirect
from .models import Task
from django.contrib.auth.decorators import login_required
from Team.models import Character
from django.db.models import Q

@login_required
def task_master(request):
    user = request.user
    character = Character.objects.get(user=user)

    # Remove completed tasks
    Task.objects.filter(user=user, is_completed=True).delete()

    # Count existing tasks for the user
    existing_tasks_count = Task.objects.filter(user=user).count()

    # Check if the character has an active task
    character.has_active_task = Task.objects.filter(user=user, is_active=True).exists()

    # Calculate how many more tasks can be activated
    remaining_tasks_count = 3 - existing_tasks_count

    # Check and activate tasks based on character level and remaining task count
    tasks_to_activate = []
    if remaining_tasks_count > 0:
        if character.level >= 1:
            tasks_to_activate.append({
                'task_name': f"Defeat {int(10 * (0.5 * character.level))} enemies",
                'task_description': f"Defeat {int(10 * (0.5 * character.level))} enemies in battle.",
                'enemies_to_defeat': int(10 * (0.5 * character.level)),
                'gold_reward': int(50 * character.level)
            })
            remaining_tasks_count -= 1

        if remaining_tasks_count > 0 and character.level >= 1:
            tasks_to_activate.append({
                'task_name': f"Collect {int(100 * character.level)} gold",
                'task_description': f"Collect a total of {int(100 * character.level)} gold from battles or quests.",
                'gold_to_earn': int(100 * character.level),
                'gold_reward': int(100 * character.level)
            })
            remaining_tasks_count -= 1

        if remaining_tasks_count > 0 and character.level >= 1:
            tasks_to_activate.append({
                'task_name': f"Defeat {int(10 * (0.5 * character.level))} players",
                'task_description': f"Defeat {int(10 * (0.5 * character.level))} other players in player vs. player battles.",
                'players_to_defeat': int(10 * (0.5 * character.level)),
                'gold_reward': int(200 * character.level)
            })
            remaining_tasks_count -= 1

        # Activate tasks
        for task_data in tasks_to_activate:
            Task.objects.create(
                user=user,
                task_name=task_data['task_name'],
                task_description=task_data['task_description'],
                enemies_to_defeat=task_data.get('enemies_to_defeat', 0),
                gold_to_earn=task_data.get('gold_to_earn', 0),
                players_to_defeat=task_data.get('players_to_defeat', 0),
                gold_reward=task_data['gold_reward'],
                is_completed=False,
                is_active=False
            )

    # Retrieve tasks for the user
    tasks = Task.objects.filter(user=user)

    return render(request, 'Tavern/task_master.html', {'tasks': tasks, 'character': character})


@login_required
def activate_task(request, task_id):
    user = request.user
    existing_active_task = Task.objects.filter(user=user, is_active=True).first()

    if existing_active_task:
        # Redirect if there's already an active task
        return redirect('Tavern:task_master')

    task = Task.objects.get(pk=task_id)
    character = Character.objects.get(user=user)

    # Set character's progress for the new task
    character.killed_monsters = 0
    character.collected_gold = 0
    character.killed_players = 0
    character.save()

    # Activate the selected task
    task.is_active = True
    task.save()
    return redirect('Tavern:task_master')


@login_required
def complete_task(request, task_id):
    task = Task.objects.get(pk=task_id)
    character = Character.objects.get(user=request.user)

    # Check if there's an active task; if yes, redirect back
    #if Task.objects.filter(user=request.user, is_active=True).exists():
        #return redirect('Tavern:task_master')

    if task.is_active and not task.is_completed:
        if task.enemies_to_defeat > 0 and character.killed_monsters < task.enemies_to_defeat:
            return redirect('Tavern:task_master')

        elif task.gold_to_earn > 0 and character.collected_gold < task.gold_to_earn:
            return redirect('Tavern:task_master')

        elif task.players_to_defeat > 0 and character.killed_players < task.players_to_defeat:
            return redirect('Tavern:task_master')

        # Player has met the task requirements, grant reward and mark task as completed
        character.gold += int(task.gold_reward)
        character.save()

        task.is_completed = True
        task.is_active = False
        task.save()

    return redirect('Tavern:task_master')

@login_required
def claim_reward(request, task_id):
    task = Task.objects.get(pk=task_id)
    character = Character.objects.get(user=request.user)

    if task.is_completed:
        if task.gold_reward > 0:
            character.gold += int(task.gold_reward)
            character.save()

        # Reset task progress
        character.killed_monsters = 0
        character.collected_gold = 0
        character.killed_players = 0
        character.save()

        # Reset task
        task.is_completed = False
        task.save()

    return redirect('Tavern:task_master')

@login_required
def reset_tasks(request):
    user = request.user

    # Delete all user tasks
    Task.objects.filter(user=user).delete()


    return redirect('Tavern:task_master')

LoSaS/Tavern/templates/Tavern/task_master.html
{% extends "Home/base.html" %}

{% load static %}

{% block content %}
    <body style="background-image: url('{% static 'background/Tavern.jpg' %}'); background-size: cover; background-repeat: no-repeat;">
        <div class="container">
            <h1 class="text-center " style="background-color: DarkGray; color: black; font-weight: bold;">Your Tavern Tasks</h1>
            <div class="text-center mt-2">
                <a href="{% url 'Tavern:reset_tasks' %}" class="btn btn-danger">Reset All Tasks</a>
            </div>
            <div class="row">
                {% for task in tasks %}
                    <div class="col-md-4 mt-2 text-center">
                        <div class="card mb-4" style="background-color: DarkGray; color: black;">
                            <div class="card-body">
                                <h4 class="card-title"><strong>{{ task.task_name }}</strong></h4>
                                <b class="card-text">Description: </b>
                                <p>{{ task.task_description }}</p>
                                <p class="card-text">Gold Reward: {{ task.gold_reward }}</p>

                                {% if task.enemies_to_defeat > 0 %}
                                    <p class="card-text">Enemies to Defeat: {{ task.enemies_to_defeat }}</p>
                                {% endif %}
                                {% if task.gold_to_earn > 0 %}
                                    <p class="card-text">Gold to Earn: {{ task.gold_to_earn }}</p>
                                {% endif %}
                                {% if task.players_to_defeat > 0 %}
                                    <p class="card-text">Players to Defeat: {{ task.players_to_defeat }}</p>
                                {% endif %}

                                {% if not task.is_completed %}
                                    {% if not task.is_active and not character.has_active_task %}
                                        <a href="{% url 'Tavern:activate_task' task.id %}" class="btn btn-success">Activate Task</a>
                                    {% else %}
                                        {% if task.is_active %}
                                            <p class="card-text">Task Active</p>
                                            {% if task.enemies_to_defeat > 0 %}
                                                <p class="card-text">(Progress: {{ character.killed_monsters }})</p>
                                            {% endif %}
                                            {% if task.gold_to_earn > 0 %}
                                                <p class="card-text">(Progress: {{ character.collected_gold }})</p>
                                            {% endif %}
                                            {% if task.players_to_defeat > 0 %}
                                                <p class="card-text">(Progress: {{ character.killed_players }})</p>
                                            {% endif %}
                                            <a href="{% url 'Tavern:complete_task' task.id %}" class="btn btn-primary">Complete Task</a>
                                        {% elif character.has_active_task %}
                                            <p class="card-text">Another task is already active</p>
                                        {% endif %}
                                    {% endif %}
                                {% else %}
                                    <p class="card-text">Task Completed</p>
                                    <a href="{% url 'Tavern:claim_reward' task.id %}" class="btn btn-info">Claim Reward</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="text-center">
                <p><a class="btn btn-primary border border-secondary mt-3" href="{% url 'World:main' %}" style="background-color: DarkGray; color: black; font-weight: bold;">Go back to World</a></p>
            </div>
        </div>
    </body>
{% endblock content %}