LoSaS/Cities/urls.py
from django.urls import path
from . import views

app_name = 'Cities'

urlpatterns = [
    path('cities/', views.cities, name='cities'),
]

LoSaS/Fight/urls.py
from django.urls import path
from . import views

app_name = 'Fight'
urlpatterns = [
    path('battle/', views.battle, name='battle'),
    path('countdown/', views.countdown, name='countdown'),
    path('fight_selector/', views.fight_selector, name='fight_selector'),
]

LoSaS/Home/urls.py
""" Defines URL patterns for Home. """

from django.urls import path

from . import views

app_name = 'Home'
urlpatterns = [
    path('', views.home, name='home')
]

LoSaS/Inventory/urls.py
from django.urls import path
from . import views

app_name = 'Inventory'
urlpatterns = [
    path('equipment/', views.inventory, name='equipment'),
]

LoSaS/LoSaS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('team/', include('Team.urls')),
    path('users/', include('Users.urls')),
    path('world/', include('World.urls')),
    path('bots_farm/', include('Bots_Farm.urls')),
    path('fight', include('Fight.urls')),
    path('items', include('Items.urls')),
    path('inventory', include('Inventory.urls')),
    path('cities/', include('Cities.urls')),
    path('blacksmith/', include('Blacksmith.urls')),
    path('arena/', include('Arena.urls')),
    path('tavern/', include('Tavern.urls')),
    path('jeweler/', include('Jeweler.urls')),
    path('carpentry_shop/', include('Carpentry_Shop.urls')),
    path('clothier/', include('Clothier.urls')),
    path('armorer/', include('Armorer.urls')),
    path('boss_fight/', include('Boss_Fight.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

LoSaS/Team/urls.py
from django.urls import path
from . import views

app_name = 'Team'
urlpatterns = [
    path('create_character/', views.create_character, name='create_character'),
    path('character_list/', views.character_list, name='character_list'),
]

LoSaS/World/urls.py
""" Defines URL patterns for World. """

from django.urls import path

from . import views

app_name = "World"
urlpatterns = [
    path('main/', views.main , name='main')
]

LoSaS/World/models.py
from django.db import models

# Create your models here.

LoSaS/World/views.py
from django.shortcuts import render
from Team.models import Character

def main(request):
    user_character = Character.objects.filter(user=request.user).first()
    user_character_exists = user_character is not None
    return render(request, 'World/main.html', {'user_character_exists': user_character_exists})

LoSaS/World/templates/World/main.html
{% extends "Home/base.html" %}

{% load static %}

{% block content %}
    <body style="background-image: url('{% static 'background/Background.jpg' %}'); background-size: cover; background-repeat: no-repeat;">
        <div class="container-md-6 mx-auto text-center">
            <h2 style="background-color: DarkGray; color: black; font-weight: bold;">Welcome to the World</h2>
            <ul class="list-group">
                {% if user_character_exists %}
                    <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                        <a href="{% url 'Cities:cities' %}">City</a>
                    </li>
                    <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                        <a href="{% url 'Fight:fight_selector' %}">Fight</a>
                    </li>
                    <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                        <a href="{% url 'Inventory:equipment'%}">Inventory</a>
                    </li>
                    <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                        <a class="nav-link" href="{% url 'Team:character_list' %}">Team</a>
                    </li>


                {% else %}
                    <div style="background-color: DarkGray; color: black; font-weight: bold;">
                        <p>You must create a character to access this content.</p>
                    </div>
                    <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                        <a href="{% url 'Team:create_character' %}" class="btn btn-primary">Create Character</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </body>
{% endblock content %}