LoSaS/Armorer/urls.py
from django.urls import path
from . import views

app_name = 'Armorer'

urlpatterns = [
    path('armorer/', views.armorer, name='armorer'),
]

LoSaS/Cities/urls.py
from django.urls import path
from . import views

app_name = 'Cities'

urlpatterns = [
    path('cities/', views.cities, name='cities'),
]

LoSaS/Home/urls.py
""" Defines URL patterns for Home. """

from django.urls import path

from . import views

app_name = 'Home'
urlpatterns = [
    path('', views.home, name='home')
]

LoSaS/Jeweler/urls.py
from django.urls import path
from . import views

app_name = 'Jeweler'

urlpatterns = [
    path('jeweler/', views.jeweler, name='jeweler'),
]

LoSaS/LoSaS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('team/', include('Team.urls')),
    path('users/', include('Users.urls')),
    path('world/', include('World.urls')),
    path('bots_farm/', include('Bots_Farm.urls')),
    path('fight', include('Fight.urls')),
    path('items', include('Items.urls')),
    path('inventory', include('Inventory.urls')),
    path('cities/', include('Cities.urls')),
    path('blacksmith/', include('Blacksmith.urls')),
    path('arena/', include('Arena.urls')),
    path('tavern/', include('Tavern.urls')),
    path('jeweler/', include('Jeweler.urls')),
    path('carpentry_shop/', include('Carpentry_Shop.urls')),
    path('clothier/', include('Clothier.urls')),
    path('armorer/', include('Armorer.urls')),
    path('boss_fight/', include('Boss_Fight.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

LoSaS/Tavern/urls.py
from django.urls import path
from . import views

app_name = 'Tavern'
urlpatterns = [
    path('task_master/', views.task_master, name='task_master'),
    path('activate_task/<int:task_id>/', views.activate_task, name='activate_task'),
    path('complete_task/<int:task_id>/', views.complete_task, name='complete_task'),
    path('claim_reward/<int:task_id>/', views.claim_reward, name='claim_reward'),
    path('reset_tasks/', views.reset_tasks, name='reset_tasks'),  # Nowa ścieżka
]

LoSaS/World/urls.py
""" Defines URL patterns for World. """

from django.urls import path

from . import views

app_name = "World"
urlpatterns = [
    path('main/', views.main , name='main')
]

LoSaS/Cities/models.py
from django.db import models

# Create your models here.

LoSaS/Cities/views.py
from django.shortcuts import render

def cities(request):
    return render(request, 'Cities/cities.html')

LoSaS/Cities/templates/Cities/cities.html
{% extends "Home/base.html" %}

{% load static %}

{% block content %}
    <body style="background-image: url('{% static 'background/City.jpg' %}'); background-size: cover; background-repeat: no-repeat;">
        <div class="container-md-6 mx-auto text-center ">
            <h2 style="background-color: DarkGray; color: black; font-weight: bold;">Welcome to the City</h2>
            <ul class="list-group">
                <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                    <a href="{% url 'Armorer:armorer' %}">Visit the Armorer</a>
                </li>
                <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                    <a href="{% url 'Blacksmith:blacksmith' %}">Visit the Blacksmith</a>
                </li>
                <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                    <a href="{% url 'Carpentry_Shop:carpentry_shop' %}">Visit the Carpentry Shop</a>
                </li>
                <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                    <a href="{% url 'Clothier:clothier' %}">Visit the Clothier</a>
                </li>
                <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                    <a href="{% url 'Jeweler:jeweler' %}">Visit the Jeweler</a>
                </li>
                <li class="list-group-item mt-2" style="background-color: DarkGray; color: black; font-weight: bold;">
                    <a href="{% url 'Tavern:task_master' %}">Tavern</a>
                </li>
            </ul>
            <p><a class="btn btn-primary border border-secondary mt-3" href="{% url 'World:main' %}" style="background-color: DarkGray; color: black; font-weight: bold;">Go back to World</a></p>
        </div>
    </body>
{% endblock content %}